// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IDataSource.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// moments_momentsCollection interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface Imoments_momentsCollection
    {
		Task<ObservableCollection<Entities.momentsSchema>> GetData(int pageNumber = 0);
        Task<ObservableCollection<Entities.momentsSchema>> Refresh();
		Entities.momentsSchema Previous(Entities.momentsSchema current);
		Task<Entities.momentsSchema> Next(Entities.momentsSchema current);
    }
}
