// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IDataSource.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// PhotoAlbum_PhotoAlbumCollection interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IPhotoAlbum_PhotoAlbumCollection
    {
		Task<ObservableCollection<Entities.PhotoAlbumCollectionSchema>> GetData(int pageNumber = 0);
        Task<ObservableCollection<Entities.PhotoAlbumCollectionSchema>> Refresh();
		Entities.PhotoAlbumCollectionSchema Previous(Entities.PhotoAlbumCollectionSchema current);
		Task<Entities.PhotoAlbumCollectionSchema> Next(Entities.PhotoAlbumCollectionSchema current);
    }
}
