// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   BackgroundProcessContainer.tt
using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;
using Microsoft.Practices.Unity;
using WPAppStudio.BackgroundProcess.Ioc.Interfaces;
using WPAppStudio.Repositories;
using WPAppStudio.Repositories.Base;
using WPAppStudio.Services;
using WPAppStudio.Services.Interfaces;

namespace WPAppStudio.BackgroundProcess.Ioc
{
    //
    // Unity 2.1
    // http://msdn.microsoft.com/en-us/library/hh237493.aspx
    //
    // patterns & practices - Unity
    // http://unity.codeplex.com/
    //
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class BackgroundProcessContainer : IContainer
    {
        private readonly IUnityContainer _currentContainer;

        public BackgroundProcessContainer()
        {
            _currentContainer = new UnityContainer();

						_currentContainer.RegisterType<IJsonDataSource, JsonDataSource>();
			_currentContainer.RegisterType<IStorageService, StorageService>();
            _currentContainer.RegisterType<IInternetService, InternetService>();
			
            _currentContainer.RegisterType<IWhoWeAre_WhoWeAreCollection, WhoWeAre_WhoWeAreCollection>(new ContainerControlledLifetimeManager());
            _currentContainer.RegisterType<IPhotoAlbum_PhotoAlbumCollection, PhotoAlbum_PhotoAlbumCollection>(new ContainerControlledLifetimeManager());
            _currentContainer.RegisterType<Imoments_momentsCollection, moments_momentsCollection>(new ContainerControlledLifetimeManager());
        }

        public T Resolve<T>()
        {
            return _currentContainer.Resolve<T>();
        }
    }
}
