// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ServiceLocator.tt
using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;
using IIoc=WPAppStudio.Ioc.Interfaces;
using Ioc=WPAppStudio.Ioc;
using IViewModels=WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.Services
{
    /// <summary>
    /// Implementation of the ViewModel locator service based on IoC.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class ViewModelLocatorService
    {
        // IoC container
        private readonly IIoc.IContainer _container;

        /// <summary>
        /// Initializes a new instance of the <see cref="ViewModelLocatorService" /> class.
        /// </summary>
        public ViewModelLocatorService()
        {
            _container = new Ioc.Container();
        }
		
		/// <summary>
        /// Resolve a service of type T
        /// </summary>
        /// <typeparam name="T">Type of the service.</typeparam>
        /// <returns></returns>
        public T ResolveService<T>()
        {
            return _container.Resolve<T>();
        }

        /// <summary>
        /// Gets the reference to a WhoWeAre_TutorialViewModel.
        /// </summary>
		public IViewModels.IWhoWeAre_TutorialViewModel WhoWeAre_TutorialViewModel
        {
            get { return _container.Resolve<IViewModels.IWhoWeAre_TutorialViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a moments_DetailViewModel.
        /// </summary>
		public IViewModels.Imoments_DetailViewModel moments_DetailViewModel
        {
            get { return _container.Resolve<IViewModels.Imoments_DetailViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a PhotoAlbum_DetailViewModel.
        /// </summary>
		public IViewModels.IPhotoAlbum_DetailViewModel PhotoAlbum_DetailViewModel
        {
            get { return _container.Resolve<IViewModels.IPhotoAlbum_DetailViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a WhoWeAre_DetailViewModel.
        /// </summary>
		public IViewModels.IWhoWeAre_DetailViewModel WhoWeAre_DetailViewModel
        {
            get { return _container.Resolve<IViewModels.IWhoWeAre_DetailViewModel>(); }
        }
		/// <summary>
        /// Gets the reference to a AboutViewModel.
        /// </summary>
		public IViewModels.IAboutViewModel AboutViewModel
        {
            get { return _container.Resolve<IViewModels.IAboutViewModel>(); }
        }
		
		/// <summary>
        /// Gets the reference to a LicenseViewModel.
        /// </summary>
		public IViewModels.ILicenseViewModel LicenseViewModel
        {
            get { return _container.Resolve<IViewModels.ILicenseViewModel>(); }
        }
    }
}
