// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// moments_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface Imoments_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentmomentsSchema property.
        /// </summary>
		Entities.momentsSchema CurrentmomentsSchema { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramamoments_Detail0 property.
        /// </summary>
		bool HasNextpanoramamoments_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramamoments_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramamoments_Detail0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechmoments_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechmoments_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the Sharemoments_DetailStaticControlCommand command.
        /// </summary>
		ICommand Sharemoments_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartmoments_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartmoments_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the Nextpanoramamoments_Detail0 command.
        /// </summary>
		ICommand Nextpanoramamoments_Detail0 { get; }

        
        /// <summary>
        /// Gets the Previouspanoramamoments_Detail0 command.
        /// </summary>
		ICommand Previouspanoramamoments_Detail0 { get; }

	}
}
