// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// PhotoAlbum_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IPhotoAlbum_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentPhotoAlbumCollectionSchema property.
        /// </summary>
		Entities.PhotoAlbumCollectionSchema CurrentPhotoAlbumCollectionSchema { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramaPhotoAlbum_Detail0 property.
        /// </summary>
		bool HasNextpanoramaPhotoAlbum_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramaPhotoAlbum_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramaPhotoAlbum_Detail0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechPhotoAlbum_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechPhotoAlbum_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the SharePhotoAlbum_DetailStaticControlCommand command.
        /// </summary>
		ICommand SharePhotoAlbum_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartPhotoAlbum_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartPhotoAlbum_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the NextpanoramaPhotoAlbum_Detail0 command.
        /// </summary>
		ICommand NextpanoramaPhotoAlbum_Detail0 { get; }

        
        /// <summary>
        /// Gets the PreviouspanoramaPhotoAlbum_Detail0 command.
        /// </summary>
		ICommand PreviouspanoramaPhotoAlbum_Detail0 { get; }

	}
}
